src/lists/urls.py
from django.urls import path

from .views import (
	ListListView,
	ListDetailView,
	ListUpdateView,
	ListDeleteView,
	ListCreateView,
	ListSortView,
	
	TaskUpdateView,
	TaskDeleteView,
	TaskToggleDoneView,
	
	ToggleHideFinishedTasksView,
)

urlpatterns = [
	path("<int:pk>/", ListDetailView.as_view(), name="list_detail"),
	path("<int:pk>/edit/", ListUpdateView.as_view(), name="list_edit"),
	path("<int:pk>/delete/", ListDeleteView.as_view(), name="list_delete"),
	path("new/", ListCreateView.as_view(), name="list_new"),
	path("<int:pk>/sort/", ListSortView.as_view(), name="list_sort"),
	
	path("task/<int:pk>/edit", TaskUpdateView.as_view(), name="task_edit"),
	path("task/<int:pk>/delete", TaskDeleteView.as_view(), name="task_delete"),
	path("task/<int:task_id>/toggle_done/", TaskToggleDoneView.as_view(), name="task_toggle_done"),
	
	path("frontend-options/toggle-hide-finished-tasks/", ToggleHideFinishedTasksView.as_view(), name="toggle_hide_finished_tasks"),
	
	path("", ListListView.as_view(), name="list_list"),
]

src/todoli/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
	path("admin/", admin.site.urls),
	path("accounts/", include("accounts.urls")),  # new
	path("accounts/", include("django.contrib.auth.urls")),
	
	path("lists/", include("lists.urls")),
	path("", include("pages.urls")),
    
	path("convert/", include("guest_user.urls")),
]

src/lists/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
from django.utils.translation import gettext_lazy as _ # https://docs.djangoproject.com/en/4.2/ref/models/fields/#enumeration-types
from django.utils import timezone

import warnings

# Create your models here.

class SortCriterion(models.TextChoices):
	# https://docs.djangoproject.com/en/4.2/ref/models/fields/#enumeration-types
	BY_PRIORITY = "PR"
	BY_END_DATE = "ED"

class List(models.Model):
	title = models.CharField(max_length=255)
	#date = models.DateTimeField(auto_now_add=True)
	author = models.ForeignKey(
		settings.AUTH_USER_MODEL,
		on_delete=models.CASCADE,
	)
	sort_criterion = models.CharField(
		max_length=2,
		choices=SortCriterion.choices,
		default=SortCriterion.BY_END_DATE,
	)

	def __str__(self):
		return self.title
	
	def get_absolute_url(self):
		return reverse("list_detail", kwargs={"pk": self.pk})
	
	def sort(self):
		if self.sort_criterion == SortCriterion.BY_PRIORITY:
			return self.task_set.order_by("priority")
		elif self.sort_criterion == SortCriterion.BY_END_DATE:
			return self.task_set.order_by("end_date")
		else:
			warnings.warn("Invalid sort criterion encountered.", UserWarning)
			return self.task_set.all()

class Task(models.Model):
	list = models.ForeignKey(List, on_delete=models.CASCADE)

	title = models.CharField(max_length=255)
	#date = models.DateTimeField(auto_now_add=True)

	end_date = models.DateField() #Or DateField
	priority = models.IntegerField()
	is_done = models.BooleanField(default=False)

	def __str__(self):
		return self.title
	
	def toggle_done(self):
		self.is_done = not self.is_done
		self.save()

	def should_show_alarm(self):
		#Returns true when `end_date` is tomorrow or today
		now = timezone.now().date()
		tomorrow = now + timezone.timedelta(days=1)
		return self.end_date == now or self.end_date == tomorrow
	
class FrontendOptions(models.Model):
	user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='frontend_options')
	hide_finished_tasks = models.BooleanField(default=False)

	@classmethod
	def get(cls, user):
		try:
			frontend_options = cls.objects.get(user=user)
		except cls.DoesNotExist:
			frontend_options = cls.objects.create(user=user)
		return frontend_options

src/templates/base.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <title>{% block title %}Todoli{% endblock title %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

  <style>
    /* Custom Styles for 20s Male Style */

    /* Body Styling */
    body {
      background-color: #f8f9fa;
      font-family: Arial, sans-serif;
      color: #333;
    }

    /* Header Styling */
    .navbar-brand {
      font-size: 24px;
      font-weight: bold;
      color: #007bff;
      text-decoration: none;
    }

    .nav-link {
      font-size: 18px;
      color: #007bff;
      text-decoration: none;
    }

    .nav-link:hover {
      color: #0056b3;
    }

    /* Main Content Styling */
    .container {
      margin-top: 20px;
    }

    h1 {
      font-size: 32px;
      color: #007bff;
      margin-bottom: 20px;
    }

    p {
      font-size: 18px;
      line-height: 1.5;
    }

    /* Buttons Styling */
    .btn-outline-primary {
      color: #007bff;
      border-color: #007bff;
    }

    .btn-outline-primary:hover {
      color: #fff;
      background-color: #007bff;
      border-color: #007bff;
    }

    .btn-primary {
      background-color: #007bff;
      border-color: #007bff;
    }

    .btn-primary:hover {
      background-color: #0056b3;
      border-color: #0056b3;
    }

    /* Footer Styling */
    footer {
      background-color: #f8f9fa;
      padding: 20px 0;
      text-align: center;
      font-size: 16px;
      color: #666;
    }

    /* Custom Styles for Todoli */

    .hidden {
      color: LightGray;
    }

    .alarm {
      font-weight: 900;
    }

	.guest_username {
		font-style: italic;
	}
  </style>
</head>

<body>
  <header class="p-3 mb-3 border-bottom">
    <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
      <a class="navbar-brand" href="{% url 'home' %}">Todoli</a>
      <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
        <li><a href="{% url 'list_list' %}" class="nav-link px-2 link-dark">목록</a></li>
        {% if user.is_authenticated %}
        <li><a href="{% url 'list_new' %}" class="nav-link px-2 link-dark">목록생성</a></li>
        <li>
          <form method="post" action="{% url 'toggle_hide_finished_tasks' %}">
            {% csrf_token %}
            <button type="submit" class="btn btn-outline-primary">
              완료된 작업 숨기기
              (Current:
              {% load frontend_options_extras %}
              {{ request.user|get_hide_finished_tasks }})
            </button>
          </form>
        </li>
        </ul>
        <div class="dropdown text-end">
          <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" id="dropdownUser1"
            data-bs-toggle="dropdown" aria-expanded="false">
			{% load guest_user %}
			{% if user|is_guest_user %}
			  <span class="guest_username">Guest</span>
			{% else %}
			  <span class="non_guest_username">{{ user.username }}</span>
			{% endif %}
            
          </a>
          <ul class="dropdown-menu text-small" aria-labelledby="dropdownUser1">
            <li><a class="dropdown-item" href="{% url 'logout' %}">로그아웃</a></li>
          </ul>
        </div>
        {% else %}
        </ul>
        <div class="text-end">
          <a href="{% url 'login' %}" class="btn btn-outline-primary me-2">로그인</a>
          <a href="{% url 'signup' %}" class="btn btn-primary">회원가입</a>
        </div>
        {% endif %}
      </div>
  </header>
  <main>
    <div class="container">
      {% block content %}
      {% endblock content %}
    </div>
  </main>

  <!-- Bootstrap JavaScript Bundle -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
    crossorigin="anonymous"></script>
</body>

</html>
  

src/templates/home.html
{% extends "base.html" %}

{% block title %}Home{% endblock title %}

{% block content %}
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-6">
        <div class="card mt-5">
          <div class="card-body text-center">
            {% if user.is_authenticated %}
            <h2 class="mb-4">안녕하세요, {{ user.username }}님!</h2>
            <p><a href="{% url 'logout' %}" class="btn btn-primary">로그아웃</a></p>
            {% else %}
            <p class="mb-4">로그인하지 않았습니다</p>
            <p><a href="{% url 'login' %}" class="btn btn-primary">로그인</a> |
              <a href="{% url 'signup' %}" class="btn btn-outline-primary">회원가입</a></p>
            {% endif %}
            <p><a href="{% url 'list_list' %}" class="btn btn-link">목록보기</a></p>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

src/templates/list_delete.html
{% extends "base.html" %}

{% block content %}
  <div class="container">
    <h1>삭제</h1>
    <form action="" method="post" class="mt-4">{% csrf_token %}
      <p>"{{ list.title }}"을 삭제하시겠습니까?</p>
      <button class="btn btn-danger ml-2" type="submit">확인</button>
    </form>
  </div>
{% endblock content %}

src/templates/list_detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
  <div class="container">
    <div class="list-entry">
      <h2>{{ object.title }}</h2>
      <p><span class="text-muted">정렬 {{ object.get_sort_criterion_display }}</span></p>
    </div>
    <div>
      <p>
        <a href="{% url 'list_edit' list.pk %}" class="btn btn-primary">수정</a>
        <a href="{% url 'list_delete' list.pk %}" class="btn btn-danger">삭제</a>
        <a href="{% url 'list_sort' list.pk %}" class="btn btn-secondary">정렬</a>
      </p>

      <hr>

      <div>
        {% for task in object.sort %}
          {% include 'task_item.html' %}
        {% endfor %}
      </div>

      <hr>

      <h4>New Task</h4>
      <form action="" method="post">
        {% csrf_token %}
        {{ form | crispy }}
        <button class="btn btn-success ml-2" type="submit">저장</button>
      </form>

      <p><a href="{% url 'list_list' %}" class="btn btn-link">목록보기</a></p>
    </div>
  </div>
{% endblock content %}

src/templates/list_edit.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
  <div class="container">
    <h1>수정</h1>
    <form action="" method="post">
      {% csrf_token %}
      {{ form|crispy }}
      <button class="btn btn-info ml-2" type="submit">저장</button>
    </form>
  </div>
{% endblock content %}

src/templates/list_list.html
{% extends "base.html" %}

{% block title %}Lists{% endblock title %}

{% block content %}
  <div class="container">
    <h1>할 일 목록</h1>
    {% for list_item in list_list %}
      <div class="card">
        <div class="card-header">
          <span class="fw-bold">
            <a href="{{ list_item.get_absolute_url }}">{{ list_item.title }}</a>
          </span> &middot;
          <span class="text-muted">Sorted {{ list_item.get_sort_criterion_display }}</span>
        </div>
        <div class="card-body">
          {{ list_item.body }}
          <a href="{% url 'list_edit' list_item.pk %}">수정</a>
          <a href="{% url 'list_delete' list_item.pk %}">삭제</a>
          <a href="{% url 'list_sort' list_item.pk %}">정렬</a>
          <hr>

          <div>
            {% for task in list_item.sort %}
              {% include 'task_item.html' %}
            {% endfor %}
          </div>
        </div>
        <div class="card-footer text-center text-muted">
        </div>
      </div>
      <br />
    {% endfor %}
  </div>
{% endblock content %}

src/templates/list_new.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
  <div class="container">
    <div class="card mt-4">
      <div class="card-body">
        <h1 class="card-title">새 목록</h1>
        <form action="" method="post" class="mt-4">{% csrf_token %}
          {{ form|crispy }}
          <button class="btn btn-success ml-2" type="submit">저장</button>
        </form>
      </div>
    </div>
  </div>
{% endblock content %}

src/templates/list_sort.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
  <div class="container">
    <div class="card mt-4">
      <div class="card-body">
        <h1 class="card-title">정렬</h1>
        <form action="" method="post" class="mt-4">{% csrf_token %}
          {{ form|crispy }}
          <button class="btn btn-info ml-2" type="submit">정렬</button>
        </form>
      </div>
    </div>
  </div>
{% endblock content %}

src/templates/task_delete.html
{% extends "base.html" %}

{% block content %}
<h1 class="mt-5">Delete</h1>
<form action="" method="post" class="mt-3">
  {% csrf_token %}
  <p class="mt-4">"{{ task.title }}"을 삭제하시겠습니까?</p>
  <button class="btn btn-danger mt-3" type="submit">확인</button>
</form>
{% endblock content %}

src/templates/task_edit.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<h1 class="mt-5">수정</h1>
<form action="" method="post" class="mt-3">
  {% csrf_token %}
  {{ form|crispy }}
  <button class="btn btn-info mt-3" type="submit">확인</button>
</form>
{% endblock content %}

src/templates/task_item.html
{% load frontend_options_extras %}
<span {% if request.user|get_hide_finished_tasks and task.is_done %}class="hidden"{% endif %}>
	<span class="font-weight-bold">
		{{ task.title }} &middot;
	</span>

	{% if task.should_show_alarm %}
		<span class="alarm">
	{% else %}
		<span>
	{% endif %}
	{{ task.end_date }} &middot;
	</span>

	{{ task.priority }} &middot;
	<form method="post" action="{% url 'task_toggle_done' task.id %}" style="display: inline;">
		{% csrf_token %}
		<button type="submit" class="btn btn-link p-0">완료 여부: {{ task.is_done }}</button>
	</form> &middot;

	<a href="{% url 'task_edit' task.id %}" class="btn btn-link p-0">수정</a> &middot;
	<a href="{% url 'task_delete' task.id %}" class="btn btn-link p-0">삭제</a>
</span>

<br>